spring.application.name=skill-mentor-root
server.servlet.context-path=/api/v1
server.port=8080
spring.security.user.name=${USERNAME}
spring.security.user.password=${PASSWORD}
clerk.jwks.url=${CLERK_JWKS_URL}
clerk.api.key=${CLERK_API_KEY}

# Profile
spring.profiles.active=prod
