spring.application.name=skill-mentor-root
server.servlet.context-path=/api/v1
clerk.jwks.url=${CLERK_JWKS_URL}
clerk.api.key=${CLERK_API_KEY}
clerk.webhook.secret=${CLERK_WEBHOOK_KEY}
server.port=${PORT:8080}

# Profile
spring.profiles.active=prod
management.metrics.enable.processor=false